### ISSUE TITLE
How to Specify a version ? IE11+

### ISSUE THREAD

**Issue by TITAN9389** [duskload/react-device-detect#1]
I need to use this to show some pages on IE11+ just how can i access that ? or its not possible yet ?

**Comment by duskload** [comment]
You can acces browserMajorVersion like this:

`
import { deviceDetect } from 'react-device-detect';

...
const device = deviceDetect();
...
    return (
      <div>
           // access major version
           {device.browserMajorVersion}
      </div>
    );
  }
}
`
