### ISSUE TITLE
TypeErro: undefined is not an object ( evaluating 'nav.userAgent.toLowerCae')

### ISSUE THREAD

**Issue by blueturtle13g** [duskload/react-device-detect#101]
I get this error as I try to run it on my react native application on ios!

"react-native": "0.62.2"
react-device-detect": "^1.13.1"
macOs: catalina

**Comment by duskload** [comment]
@blueturtle13g React Native support hasn't been added yet.

**Comment by duskload** [comment]
React Native support will be added in #107.
