### ISSUE TITLE
isMobileSafari returns true when in Chrome on iPadOS(iOS13)

### ISSUE THREAD

**Issue by jiikko** [duskload/react-device-detect#106]
https://github.com/duskload/react-device-detect/pull/85

https://github.com/duskload/react-device-detect/blob/7153b078b1d95cb5c4ec6c3f04fe0a8b107925ca/src/components/helpers/selectors.js#L78

at least `isMobileSafari` returns true when in `Chrome on iPadOS(iOS13)`.
I think that `isMobileSafari` will return true with all browser on `iPadOS(iOS13)`.

**Comment by riteshpakala** [comment]
Hey @jiikko,

That is correct. All browsers on iOS are built using safari's web engine. Chrome is a wrapper over safari (webkit) on iOS that is all.

**Comment by aldrichdev** [comment]
My solution for this, because I didn't want to apply my logic to iPads as well, was to check `isMobileSafari && isMobileOnly`. This returns false for iPad.
