### ISSUE TITLE
BrowserView, MobileView, TabletView shows on iPad at the same time

### ISSUE THREAD

**Issue by artmsv** [duskload/react-device-detect#112]
1. Bug description
BrowserView, MobileView, TabletView shows on iPad at the same time
2. Steps to reproduce
Add BrowserView, MobileView, TabletView into react component, start iPad simulator on macOS, open page in safari
3. Device user-agent
`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"`
I used this user-agent in desktop chrome and the issue is not appearing.
4. Device/Browser type/name
Safari on iPad simulator, iPad (8th generation), and all pro versions with ipadOS 14
5. Share code for a better understanding (for example, here https://codesandbox.io/s/new)
https://codesandbox.io/s/priceless-williamson-r8xug?file=/src/App.js
6. Any additional info
<img width="1440" alt="Screen Shot 2020-10-08 at 11 13 58 AM" src="https://user-images.githubusercontent.com/46975989/95498418-a41bf600-0958-11eb-9e26-6340ed22210d.png">

**Comment by matthew9510** [comment]
Glad I'm not the only one. Is there any workaround that you know of at this moment @h3xsoul ? 

I know this problem doesn't appear when using chrome on the ipad, but I need to handle the safari edge case as well.

**Comment by h3xsoul** [comment]
@matthew9510 As you can see from the screenshot `isTablet` = `true` for tablets and `false` for mobile and desktops. So I used {isTablet && <BrowserView/> } in this case it will show proper view

**Comment by matthew9510** [comment]
@h3xsoul right on. Thanks

**Comment by sinnbeck** [comment]
I fixed it by making my own BrowserView which I import instead of the original one 

```
import React from 'react';
import {CustomView, isBrowser, isTablet} from "react-device-detect";

export default function BrowserView ({children, ...props}) {
    return (
        <CustomView condition={isBrowser && !isTablet} {...props}>
            {children}
        </CustomView>
    )
}
