### ISSUE TITLE
isIE cannot be detected

### ISSUE THREAD

**Issue by gyto23** [duskload/react-device-detect#115]
Browser is not recognized by any means, even testing from original library of `ua-parser-js` and trying to have this approach of 
```
const isIE = /*@cc_on!@*/false || !!document.documentMode
```
Ways to reproduce is to check user agent of the IE11 via http://faisalman.github.io/ua-parser-js/
Issue was already mention here https://github.com/faisalman/ua-parser-js/issues/455

**Comment by duskload** [comment]
Should be working now, was fixed in ua-parser-js and its version was updated.
