### ISSUE TITLE
Fetch & compare with latest available version of a browser

### ISSUE THREAD

**Issue by o1dnik** [duskload/react-device-detect#116]
**1. Feature description**

Show if the browser is being outdated.

**2. What do you suggest**

As an example, there could be a simple list of available versions like [this one](https://updatemybrowser.org/browser), but technically it's easy to subscribe to the feed of new version releases and store this info somewhere internally. A function like 'getBrowserLatestVersion' might perform the check against the browser name and return if it's being outdated or most recent.

Technically that might be similar to the [feature request](https://github.com/duskload/react-device-detect/issues/92) regarding crowlers, since there's a living updated list of web crowlers.

**Comment by duskload** [comment]
I don't think that this feature is needed for this application.
