### ISSUE TITLE
mobile detection failed when using Chrome devtool's Toggle Device Toolbar

### ISSUE THREAD

**Issue by thilllon** [duskload/react-device-detect#118]
1. Bug description
Mobile detection is failed when I am using Chrome devtool's "Toggle Device Toolbar".

2. Steps to reproduce
Open Chrome devtool and turn "toggle device toolbar" button on which is at upperleft side.
"isMobile" is set to be "false" on the console.

3. Device user-agent, 4. Device/Browser type/name
Windows 10, Chrome latest version.

**Comment by ThallyssonKlein** [comment]
Does anyone have any temporary solution to this problem?

**Comment by thilllon** [comment]
@ThallyssonKlein I did not think about that way. Thank you.
