### ISSUE TITLE
isBrowser is duplicated in index.d.ts

### ISSUE THREAD

**Issue by Svehla** [duskload/react-device-detect#12]
`isBrowser` is declared two times in typecsript interface
So my compiler is unable to build: 
`Cannot redeclare block-scoped variable isBrowser`

Thank you

**Comment by h3mpti** [comment]
I created a pull request to fix this, please accept it and release a new version :-)
PR #13

**Comment by duskload** [comment]
Thanks guys! Request accepted and released.
