### ISSUE TITLE
Support for React 17.0.1

### ISSUE THREAD

**Issue by conspireagency** [duskload/react-device-detect#122]
1. When I attempt to install on a new NextJs project (React 17.0.1) get the error described in #3 here.  Perhaps I'm missing something, but would be great to make this compatible.
2. What do you suggest
3. Found: react@17.0.1 
Could not resolve dependency:  peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-device-detect@1.14.0

**Comment by duskload** [comment]
@conspireagency Just released 1.15.0, should be working now. Please have a check
