### ISSUE TITLE
Rename `browser` to `desktop`

### ISSUE THREAD

**Issue by shuttleriiiz** [duskload/react-device-detect#131]
1. Feature description
Rename `browser` to `desktop`

2. What do you suggest
Using `browser` to refer to desktop browser is not really intuitive, because all of the devices are using "browser" to display the app.

3. Any additional info (links, screenshots, descriptions etc)

**Comment by duskload** [comment]
I wouldn't delete `isBrowser` for the sake of compatibility with previous versions but I'll add `isDesktop` as alias.

**Comment by duskload** [comment]
Added. Update package to the latest version
