### ISSUE TITLE
Can I detect the mobile webview?

### ISSUE THREAD

**Issue by dancixx** [duskload/react-device-detect#138]
Can I use this library to detect a webview like messenger or instagram?

**Comment by WebTravel** [comment]
@dancixx Why do you close it? Can you reproduce some information about detecting of webview. Now I am using `isMobileOnly` flag from this library and it doesn't work in webview. How do you detect webview now?

**Comment by ashwinkhode** [comment]
@dancixx +1

**Comment by justin-crocus** [comment]
why was this issue closed? what is the purpose of creating issue if you just close it with no info or comment @dancixx 

everyone would appreciate if at least little bit of info is provided before closing the issue
