### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by jonjamz** [duskload/react-device-detect#14]
Hi,

I don't see a way to pass a custom user agent string into this library but it seems like it should be straightforward since you are using UA Parser. Allowing for this would enable use in SSR.

See https://github.com/faisalman/ua-parser-js#using-nodejs.

If you are open to this idea, I would be happy to help with a PR.

Best,

Jon

**Comment by duskload** [comment]
Sounds good. Will look into this issue in nearest future. If you can make a PR, I will accept it gladly

**Comment by duskload** [comment]
Can you make a separated repo with the code so I can have a look on it?

**Comment by duskload** [comment]
Closing the issue, since its implementation requires major application refactoring.
I will consider it to be a part of next big release.

**Comment by christianfredh** [comment]
Lib looks very nice to use, but we need to use SSR. SSR still not supported?

**Comment by christianfredh** [comment]
Found this, so linking here to answer my question:
https://github.com/duskload/react-device-detect/issues/54
