### ISSUE TITLE
Incorrect ViewProps/CustomViewProps types

### ISSUE THREAD

**Issue by scriptex** [duskload/react-device-detect#163]
Based on the latest (v2.0.0) release, the CHANGELOG states that

> Views doesn't accept viewClassName prop anymore, use className instead.

This is not reflected in the [`ViewProps`](https://github.com/duskload/react-device-detect/blob/master/index.d.ts#L79) as well as in the [`CustomViewProps`](https://github.com/duskload/react-device-detect/blob/master/index.d.ts#L86).

Please note that this is a pure TypeScript error as the compiler complains about a missing prop when I try to use `className` instead of `viewClassName`.

There is an error when used the other way around: the old `viewClassName` makes TypeScript happy but then the browser is not happy and warns

> Warning: React does not recognize the `viewClassName` prop on a DOM element ...

but this is okay since this prop is clearly not intended to be used anymore.

Please fix this as it is pretty minor :)

I can also submit a PR if you wish.

P.S. Thanks for the awesome lib!

**Comment by duskload** [comment]
@scriptex Thanks for the report! I've published version 2.0.1 with fix.
