### ISSUE TITLE
Doesn't Update UserAgent when device change without reload - testing with Google Device Toolbar

### ISSUE THREAD

**Issue by EduardoHidalgo** [duskload/react-device-detect#17]
Hi! I love your proyect, it's really useful and i grateful. 

I use Google Device Toolbar when i need to test a responsive web page, so this tool change UA data in the air, and doesn't reload the web page when i change device.

In this context (and thinking about using "react-device-detect" as a way to detect when a page is resized) i need a way to update UA data of "react-device-detect", without reload page.

**Comment by duskload** [comment]
Was answering to the similar question in https://github.com/duskload/react-device-detect/issues/7

I think that working with resize is beyond the scope of this package.
