### ISSUE TITLE
Please add a note about using user agent sniffing 

### ISSUE THREAD

**Issue by gpoole** [duskload/react-device-detect#174]
Appreciate your work on the library and I can see that it's useful for a bunch of cases, but because it uses user-agent sniffing I think it would be helpful to include a note in your readme mentioning that it does that, along with link out to a detailed explanation for why users may or may not want to go that route. For example, this article on MDN thoroughly covers the background and I think is ideal as an explainer: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

This library ranks highly for searches like "how to check for mobile in React" and I think that may be leading to some confusion, especially for developers new to React or frontend and maybe aren't familiar with the options.

**Comment by russeg** [comment]
> ... I think it would be helpful to include a note in your readme mentioning that it does that, along with link out to a detailed explanation for why users may or may not want to go that route. 

maybe you can write it and do a pull request, since you have read the mdn doc and understood it .

> This library ranks highly for searches like "how to check for mobile in React" and I think that may be leading to some confusion, especially for developers new to React or frontend and maybe aren't familiar with the options.

what other options? this ranks highly probably because there aren't much options.

**Comment by gpoole** [comment]
> maybe you can write it and do a pull request, since you have read the mdn doc and understood it .

I'm waiting for a response from the repo owner before putting the extra effort into a PR.

> what other options? this ranks highly probably because there aren't much options.

Media queries targeting mobile device sizes via `matchMedia` are probably the best alternative approach. There are quite a few react libraries for that such as [react-responsive](https://www.npmjs.com/package/react-responsive) and [@react-hook/media-query](https://www.npmjs.com/package/@react-hook/media-query).
