### ISSUE TITLE
tabletView and mobileView showing together on ipad

### ISSUE THREAD

**Issue by Adonais0** [duskload/react-device-detect#20]
I tested with ipad 2018, if the code is `<mobileView><img src="imageA"/></mobileView> <tabletView><img src="imageB"></tabletView>`, on ipad it will show both imageA and imageB.

**Comment by duskload** [comment]
@Adonais0 Can you please give me a UA of device?

**Comment by RenoPoit** [comment]
@duskload Isn't it a normal behavior ? My understanding is that `MobileView` is designed to handle both tablets and mobiles. 

@Adonais0 If you want to handle them separately, I think you should consider using `MobileOnlyView`.

**Comment by duskload** [comment]
Thanks @RenoPoit, you are right.

@Adonais0 , if `MobileOnlyView` is not an option for you feel free to reopen this issue, with respective device user agent.

**Comment by michaelmior** [comment]
I had this experience as well. It would be helpful to include a note on this in the README when the example with `BrowserView` and `MobileView` is shown. The way the example is written gave me the impression that the two were opposites.
