### ISSUE TITLE
Current Version 2.2.2 has security vulnerability on old version of ua-parser-js

### ISSUE THREAD

**Issue by jeffxor** [duskload/react-device-detect#203]
1. Bug description

ua-parser-js  >=0.8.0 <1.0.33 || <0.7.33
Severity: high
ReDoS Vulnerability in ua-parser-js version  - https://github.com/advisories/GHSA-fhg7-m89q-25r3
ReDoS Vulnerability in ua-parser-js version  - https://github.com/advisories/GHSA-fhg7-m89q-25r3

3. Steps to reproduce
npm audit

It appears there is an existing [pull request](https://github.com/duskload/react-device-detect/pull/202) that will resolve these issues

**Comment by duskload** [comment]
Released new version `2.2.3` with a fix
