### ISSUE TITLE
ReDoS Vulnerability in ua-parser-js version

### ISSUE THREAD

**Issue by kkatusic** [duskload/react-device-detect#205]
1. Feature description

I got notification from GitHub about your dependencie **ua-parser-js** tha it jad ReDoS vulnerability.

2. What do you suggest

Update **ua-parser-js** to newver version 1.0.33

3. Any additional info (links, screenshots, descriptions etc)

![ReDoS_Vulnerability_in_ua-parser-js_version](https://user-images.githubusercontent.com/1242145/216828101-30614fd2-305e-43b7-b4ae-e4a74a0cb8e9.png)

**Comment by duskload** [comment]
Released new version `2.2.3` with a fix
