### ISSUE TITLE
this is crashing in SSR

### ISSUE THREAD

**Issue by yanv1991** [duskload/react-device-detect#21]
we are getting an error because the existence of window object is not validated

**Comment by CathyMacars** [comment]
I believe this would crash Gatsby as well, btw.
Adding `if (typeof window !== 'undefined') { ... }` should solve this.

**Comment by duskload** [comment]
Can't reproduce this one. If you still have this error please provide a reproducible example, for example, here https://codesandbox.io.

Feel free to reopen the issue then.
