### ISSUE TITLE
Add a changelog or release notes

### ISSUE THREAD

**Issue by rlreamy** [duskload/react-device-detect#22]
As a developer I want to be able to understand what was changed with new releases available through npm so that I can understand what has changed and whether I need to update.  It is also hlpful to understand what kinds of breaking changes may have been introduced.

This can be achieved through either tagged releases or a changelog.

**Comment by duskload** [comment]
Hi @rlreamy , thanks for pointing this out!

Will work on it from now.

**Comment by sergioloporto** [comment]
Hi, can you please write what changed between 1.13.1 and 1.14 ?
