### ISSUE TITLE
Kindle Fire HD not identified as mobile/tablet

### ISSUE THREAD

**Issue by smschick** [duskload/react-device-detect#23]
![img_3211](https://user-images.githubusercontent.com/10112359/53498991-0cacac80-3a6d-11e9-942a-1b86266578d6.jpg)

![img_3213](https://user-images.githubusercontent.com/10112359/53500563-33201700-3a70-11e9-98a8-4fbd8e8b1053.jpg)

As shown in the attached screenshot I've tested on two Kindle Fire HD tablets and both have the same outcome.   isMobile/isTablet is false as the device type comes back as browser/desktop.  I also went to https://faisalman.github.io/ua-parser-js/ on both Kindle fire's and they are identified as desktop/browser.   

I'm thinking about checking for the Silk user agent on top of isMobile in my application for the time being, or os of Android... not sure if that will affect some Chrome books? 

FYI, if you just test with the emulation in chrome dev tools for the Kindle Fire HD you will get the desired isMobile/Tablet: true, device is Amazon... you have to test on an actual device, and the BrowserStack emulator, if you can get it to load, will give you browser generic device/desktop as well on ua-parser-js.

**Comment by smschick** [comment]
This seems to be detecting the kindle/silk browser well.  Might be a bit over-kill with all the various build versions, or missing some.

`const isKindle = () => {
  return !!(
    getUA.match(/Kindle/i) ||
    getUA.match(/Silk/i) ||
    getUA.match(/KFTT/i) ||
    getUA.match(/KFOT/i) ||
    getUA.match(/KFJWA/i) ||
    getUA.match(/KFJWI/i) ||
    getUA.match(/KFSOWI/i) ||
    getUA.match(/KFDOWI/i) ||
    getUA.match(/KFTHWA/i) ||
    getUA.match(/KFTHWI/i) ||
    getUA.match(/KFAPWA/i) ||
    getUA.match(/KFAPWI/i)
  )
}`

**Comment by duskload** [comment]
Hi @smschick, it's been a lot of this devices (which is not being recognized correctly), and I don't think it's a good way to add support to each and single one of them to the library.

I would consider how to make this process easier though.
