### ISSUE TITLE
Crawlers vs. browser

### ISSUE THREAD

**Issue by guacamoli** [duskload/react-device-detect#28]
Hi, I currently have text animations on my website (showing only when the user scrolls to the element). However, if the content is being accessed by a crawler, I'd like to disable these animations for SEO purposes. I'm not sure if that is possible with this library and whether using `isBrowser` is enough? Any advice?

**Comment by duskload** [comment]
Hi @guacamoli, unfortunately I'm not an expert in a questions of SEO and don't now how this library can help you with it. I'd suggest you to ask this question on stackoverflow.
