### ISSUE TITLE
how to trigger isMobile based on viewport size?

### ISSUE THREAD

**Issue by movingelectrons** [duskload/react-device-detect#30]
I would like to cypress to test my views, it can set viewport size easily and its supposed to be able to set useragent but dosent seem to really work.  the viewport size is however changed, can I trigger ismobile to be true based on viewport size?

**Comment by duskload** [comment]
Hi @movingelections, thanks for your report.

This package changes isMobile prop based on User Agent update, so here is no handle or hook to change it manually on viewport resize. You probably should use case media queries for this purpose, or add event listener to window resize and xhech is mobile there.
