### ISSUE TITLE
problem getting cypress tests to trigger isMobile

### ISSUE THREAD

**Issue by movingelectrons** [duskload/react-device-detect#31]
Hello, Im not sure if this is a issue with react-device-detect, cypress, or my own fault, but I have this line in my cypress spec at the very top,

Cypress.config('user-agent', 'mobile')

it does not trigger isMobile when I run cypress.  I was able to get cypress to trigger isMobile with a cypress.json config file at root of project, with contents of

{
    "chromeWebSecurity": false,
    "baseUrl": "http://localhost:3000",
    "userAgent": "Mozilla/5.0 (Linux; Android 6.0.1; SM-G532G Build/MMB29T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.83 Mobile Safari/537.36"
}

but doing it like this is lame because it makes ALL cypress tests run as mobile, when I really want to be able to do it in each test file like the above.. ty in advance!

**Comment by duskload** [comment]
@movingelectrons,

What I see from `Cypress` documentation, you set a value `mobile` to `user-agent` property in config. Which isn't look like a valid mobile user-agent. Try to find a valid user-agent and set it to config.

**Comment by movingelectrons** [comment]
Do you mean 

Cypress.config('user-agent', "Mozilla/5.0 (Linux; Android 6.0.1; SM-G532G Build/MMB29T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.83 Mobile Safari/537.36")

?  I tried that right after I tried just setting it to 'mobile'.  I guess I should have mentioned that ... same problem however.

**Comment by ykavi** [comment]
if you are using user agent for mobile information
      cy.visit(yourUrl, {
        headers: {
          'user-agent': 'Mozilla/5.0 (Linux; U; Android 4.3; en-us; SM-N900T Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30',
        }
      });
