### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by gyerts** [duskload/react-device-detect#32]
I've just installed this app, and put next code into the test component
```html
<BrowserView>
     <h1> This is rendered only in browser </h1>
</BrowserView>
<MobileView>
     <h1> This is rendered only on mobile </h1>
</MobileView>
```
As result I have typescript compilation error:

> JSX element type 'BrowserView' is not a constructor function for JSX elements.
>   Type 'BrowserView' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.  TS2605

I've tried to install `@types/react-device-detect` but there is no package found in npm repo

**Comment by gyerts** [comment]
solved by adding option to typescript.json

```
{
  "compilerOptions": {
    "jsx": "react",
  },
}
```
Solution found here: https://github.com/Microsoft/TypeScript/issues/30108

**Comment by gyerts** [comment]
I solved by adding a trick, which is temporary solution for testing your library
```
import { BrowserView as BrowserViewOrig, MobileView as MobileViewOrig } from "react-device-detect";

const BrowserView: any = BrowserViewOrig;
const MobileView: any = MobileViewOrig;
```
Now it works, any ideas how to solve this issue without tricks?

**Comment by duskload** [comment]
Hi @gyerts, thanks for your report.

I will have a look on this typings issue.

**Comment by duskload** [comment]
@gyerts , updated and merged.
