### ISSUE TITLE
In-App Safari

### ISSUE THREAD

**Issue by robhung** [duskload/react-device-detect#38]
Is there a way to differentiate MobileSafari and In-App Mobile Safari?

While they are supposed to be the same browser, In-App Mobile Safari currently [doesn't support WebRTC](https://bugs.webkit.org/show_bug.cgi?id=183201) so I'm needing to re-direct users to use the actual Mobile Safari app.

**Comment by duskload** [comment]
Hi @robhung. What is in-app mobile safari? Could you provide boh browsers user agents?

**Comment by robhung** [comment]
The browser that's used inside other apps, eg. Mail, Facebook, Slack, etc. Similar to [this issue](https://github.com/fnando/browser/issues/179). I think the share the same user agents, but the thread I linked in my original post shows they can exhibit different behaviour.

Slack iOS: Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1

Safari iOS: Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1

**Comment by StampixSMO** [comment]
@duskload Not sure why this is closed, `isSafari()` and `isMobileSafari()` still don't correctly detect WKWebView on iOS (= in-app browser)

**Comment by StampixSMO** [comment]
`getBrowser().name` returns `Facebook` instead of `Mobile Safari`
