### ISSUE TITLE
Suggestion to add Smart-Tv's

### ISSUE THREAD

**Issue by ejbp** [duskload/react-device-detect#4]
Would be nice if you could add detection and views for smart-tv's. Thanks

**Comment by duskload** [comment]
I definitely want.

But for now, I don't have access to Smart TV to test it on.  But i hope i will have one, in a nearest future.

**Comment by duskload** [comment]
@ejbp Added smart tv support.
You can update your package and check it.

**Comment by ejbp** [comment]
I will definitely do that. Thanks for the update!

**Comment by ejbp** [comment]
I've tested with an webos LG smart tv and isSmartTV is returning false. Here is the output:

 ```
OnDeviceDetect.js is SmartTv? false 
Object {isBrowser: true, browserMajorVersion: undefined, browserFullVersion: undefined, browserName: "Safari", engineName: "WebKit"…}
browserFullVersion: undefined
browserMajorVersion: undefined
browserName: "Safari"
engineName: "WebKit"
engineVersion: "538.2"
isBrowser: true
osName: "Linux"
osVersion: undefined
userAgent: "Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/538.2 (KHTML, like Gecko) Large Screen WebAppManager Safari/538.2"
__proto__: Object}

isBrowser: true, isSmartTV: false, isMobile: false
```

note: I'm running it inside an webos web app.
