### ISSUE TITLE
How to use properties

### ISSUE THREAD

**Issue by Fettabachi** [duskload/react-device-detect#5]
How could I utilize `browserName` to return the browser being used?

**Comment by duskload** [comment]
```
import { browserName } from 'react-device-detect';

...
render () {
  if (browserName === 'Firefox') {
    return <div> {...content} </div>
  }
  return <div> {... other content} </div>
```

I can help you more if you provide more information what do you want to use it for.

**Comment by Fettabachi** [comment]
I’d like to detect which browser is being used and add a class to the html
or app container like Layout-Engine
https://github.com/stowball/Layout-Engine

Thanks,
Tim

On March 30, 2018 at 1:33:33 PM, Michael (notifications@github.com) wrote:

import { browserName } from 'react-device-detect';

...
render () {
  if (browserName === 'Firefox') {
    return <div> {...content} </div>
  }
  return <div> {... other content} </div>

I can help you more if you provide more information what do you want to use
it for.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/duskload/react-device-detect/issues/5#issuecomment-377577648>,
or mute the thread

**Comment by duskload** [comment]
Sorry that it takes so much time for answer.

You can use this properties like: browserName, browserVersion (and every other which returns strings) and pass them directly to className prop like this:

```
<div className={`${browserName.toLowerCase()}-${brpwserVersion}`}>
   {...content}
</div>
```

and create css for each browser or browser version, like

```
.chrome-65 {
color: 'ddd'
display: flex;
...
}
```

And like this, for every browser or browserVersion if you want for them to have different styles.
