### ISSUE TITLE
Generic type ReactComponentElement error

### ISSUE THREAD

**Issue by manemmao** [duskload/react-device-detect#51]
throw typescript error with latest packages below;

- "react-device-detect": "^1.9.9",
- "@types/react": "16.9.2", 

`ERROR in ..../node_modules/react-device-detect/index.d.ts
ERROR in .../node_modules/react-device-detect/index.d.ts(75,53):
TS2707: Generic type 'ReactComponentElement<T, P>' requires between 1 and 2 type arguments.`

it could be ok just adding `<any>` to line 75 of index.d.ts

**Comment by duskload** [comment]
@manemmao, Thanks for your report! The issue is fixed and deployed.
