### ISSUE TITLE
How can I use this module for server side rendering?

### ISSUE THREAD

**Issue by boryslee111** [duskload/react-device-detect#53]
Hi
Thanks for your module.
This is a small and useful module for the React frontend.
But I can't use this module for server-side rendering.
I think if we can use this module for server-side rendering, this module will be more useful and grateful.
we can analyze request user agent string on the server-side.
I think internal functions will be exported to analyze user agent in this module.
what about your thoughts?
Or can I use this module for server-side rendering now?

**Comment by duskload** [comment]
Hi @boryslee111, can you share an example of ssr app with a react-device-detect not working?

**Comment by duskload** [comment]
Gonna close this issue as duplicate of #54 where I plan to work on SSR.
