### ISSUE TITLE
SSR device detection is not working

### ISSUE THREAD

**Issue by novonimo** [duskload/react-device-detect#54]
I'm using react-device-detect in next.js (react SSR) but it doesn't work.

There are some closed issues about SSR in the repo but I think it isn't implemented yet.

next version: 9.0.5
react-device-detect:  1.9.10

**Comment by duskload** [comment]
Hi @novonimo , can you share a "not working" example with me? Maybe in separeted repo?

I just bootstrapped a next.js quick start app connected with "react-device-detect" and it seems work fine.

**Comment by adamsoffer** [comment]
I can confirm I'm also getting an issue using this library with ssr. I'm using next.js v9.0.5. The error I'm seeing:
```
Text content did not match. Server: "OrchestratorsShapeSearchwalletConnect Wallet" Client: "The Livepeer Explorer Beta is currently unavailable on mobile." 
    in div (created by Context.Consumer)
    in Context.Consumer (created by Context.Consumer)
    in Context.Consumer (created by EmotionCssPropInternal)
    in EmotionCssPropInternal (at main.tsx:53)
    in Anonymous (at pages/​index.tsx:66)
    in Anonymous (at apollo.tsx:19)
    in withApollo(Component) (at _app.tsx:28)
    in MyApp
```

**Comment by duskload** [comment]
Hi @adamsoffer , can you share a code snippet how you use ‘rdd‘ in next.js?

**Comment by christianfredh** [comment]
Is there an example somewhere using this library with SSR?

**Comment by DragonBlack** [comment]
Hi @duskload.
You use UAParser module for parsing User-Agent which use object "window" for get User-Agent. But on SSR "window" object is undefined.
Try disable JavaScript on browser and run this code:
```
import { osName } from 'react-device-detect'
const MainPage: NextPage = (props) => {
    return (
        <>
              {osName}
        </>
    );
};
export default MainPage;
```
You will see "none", but with enabled JS you will see your browser name.
P.S. Sorry for my English

**Comment by duskload** [comment]
Is issue still reproduces after last update?

**Comment by duskload** [comment]
Check on version 1.11.14.

If issue is still relevant - reopen an issue or create new one.

**Comment by hrahimi270** [comment]
@duskload I checked with the latest version (1.11.14) in a Next.js project.
I think the problem is that the detection not working on the initial request (hard reload of page).
But after updating dom (on client-side with React) it works.

**Comment by kid-three** [comment]
So, is this working and reliable?

**Comment by zeckdude** [comment]
This is still not working. Other libraries such as https://github.com/kaimallea/isMobile#use let you specify the useragent on the server-side.

**Comment by czco** [comment]
Not sure why this was closed. I've created a new issue here with a sample repo [Issue #75 ](https://github.com/duskload/react-device-detect/issues/75)

**Comment by andreademasi** [comment]
Bump

**Comment by JohnAllen** [comment]
Is there a recommended or canonical way of doing this with NextJS?

**Comment by aravindanve** [comment]
I wanted to pre-render a page conditionally based on the device type on React/NextJS/SSR. I was able to do it by storing the user-agent in a context and reading it from a hook `useIsMobile()` which returned true or false based on the parsed user-agent header on the server side.

We create a context to store the parsed user-agent header.
```ts
// userAgentContext.ts
import { userAgent } from "next/server";
import { createContext } from "react";

export type UserAgent = ReturnType<typeof userAgent>;
export const UserAgentContext = createContext<UserAgent | undefined>(undefined);
```

We create a hook to consume the context and check device type.
```ts
// useIsMobile.ts
import { useContext } from "react";
import { UserAgentContext } from "./userAgentContext.ts";

export const useIsMobile = () => {
  const userAgent = useContext(UserAgentContext);
  if (!userAgent) {
    throw new Error("useIsMobile must be used within a UserAgentContext.Provider");
  }

  return userAgent.device.type === "mobile";
};
```

We can use a sever component as the layout (app router) to get the user agent from request headers
```ts
// layout.tsx
"use server";

import { headers } from "next/headers";
import { userAgent } from "next/server";
import { LayoutClient } from "./layoutClient.ts";

export default async function Layout({ children }: { children: React.ReactNode }) {
  const reqUserAgent = userAgent({ headers: headers() });
  return <LayoutClient reqUserAgent={reqUserAgent}>{children}</LayoutClient>
}

```

We can then pass the user agent to a client component that will provide the initial value for the context. Since client components with `"use client"` directive are still rendered once on the server with initial values then hydrated on the client.
```ts
// layoutClient.tsx
"use client";

import { UserAgentContext } from "./userAgentContext.ts";

export default function LayoutClient({ reqUserAgent, children }: { reqUserAgent: UserAgent, children: React.ReactNode }) {
  return <UserAgentContext.Provider value={reqUserAgent}>{children}</UserAgentContext.Provider>;
}

```

Now when this page is rendered for the first time on the server with initial values, useIsMobile() should accurately return a value based on the user-agent device type.
```ts
// page.tsx
"use client";

export default function Page() {
  const isMobile = useIsMobile();

  return isMobile ? <>Mobile</> : <>Desktop</>;
}
```
