### ISSUE TITLE
iPad iOS 13 not detected as tablet

### ISSUE THREAD

**Issue by samuelint** [duskload/react-device-detect#55]
Since iOS 13 browser is declared as a desktop browser, isTablet and even isIOS do not work properly on iPad.

This guy use a different algorithm to detect iPad https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct .

would it be possible to implement this for `isTablet`?

Thank you

**Comment by duskload** [comment]
@samuelint 

I've added a couple of methods, it should be working now but it needs to be tested.

New methods are:

`isIOS13`
`isIPad13`
`isIPhone13`
`isIPod13`

Please tell if it's actually worked. Thanks!

**Comment by guntherkoo** [comment]
@duskload : Does this not work on iOS simulator version of iPad 12.9inch? Thanks!

**Comment by chepicov** [comment]
@duskload why not to add `isIPad13` to `isTablet` selector?

**Comment by puneetverma05** [comment]
doesn't work on iPad, ios 15.5 #193
