### ISSUE TITLE
isIE = false on IE11 

### ISSUE THREAD

**Issue by GigiSan** [duskload/react-device-detect#6]
It appears that on IE11 the variable isIE is set to false.
I tried this page on Chrome and Mobile and the respective variables changed accordingly, but not for IE11.

Am I doing something wrong?

Thanks in advance for your replies. Have a nice day ☺

Test with IE11:
![scr1](https://user-images.githubusercontent.com/22095380/38487593-0856091e-3be1-11e8-8e6c-973e9740127a.PNG)

Test with Chrome+Mobile mode:
![scr2](https://user-images.githubusercontent.com/22095380/38487950-30093cb4-3be2-11e8-8f4e-80faf4aa3489.png)

Test with Chrome+Desktop mode:
![scr3](https://user-images.githubusercontent.com/22095380/38487991-4c2962ca-3be2-11e8-8a4e-d901810afd15.png)

**Comment by GigiSan** [comment]
Looks like "browserName" is correctly set to "IE" in this case so as an immediate solution I can test that. Wouldn't be bad if the bool would be fixed though. ☺

![scr4](https://user-images.githubusercontent.com/22095380/38488278-3d1241e8-3be3-11e8-9926-714c17d8d554.png)

**Comment by duskload** [comment]
I've fixed this. You can update package and check if it works.

Feel free to reopen the issue if problem persist.

Thanks for your report!
