### ISSUE TITLE
Gatsbyjs: "navigator" is not available during server side rendering

### ISSUE THREAD

**Issue by stzonis** [duskload/react-device-detect#60]
Hi,
This library was working with gatsbyjs (1.9.10) until the last version (1.11.11). I am getting now this error:

failed Building static HTML for pages - 5.562s
 ERROR #95312 
"navigator" is not available during server side rendering.
See our docs page for more info on this error: https://gatsby.dev/debug-html

  416 | 
  417 | var getIOS13 = function getIOS13() {
> 418 |   return (/iPad|iPhone|iPod/.test(navigator.platform) || navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1) && !window.MSStream;
      | ^
  419 | };
  420 | 
  421 | var getIPad13 = function getIPad13() {

  WebpackError: ReferenceError: navigator is not defined
  
  - main.js:418 getIOS13
    node_modules/react-device-detect/main.js:418:1
  
  - main.js:507 Object../node_modules/react-device-detect/main.js
    node_modules/react-device-detect/main.js:507:1

**Comment by duskload** [comment]
Hi @stzonis, I will look on it shortly. Thanks!

**Comment by duskload** [comment]
@stzonis, uploaded a fix, can you update and have a look?

**Comment by Fluorz** [comment]
Same error here

```
/node_modules/react-device-detect/main.js:423
return (/iPad|iPhone|iPod/.test(navigator.platform) || navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1) && !window.MSStream;

ReferenceError: navigator is not defined
```

**Comment by stzonis** [comment]
With the version "1.11.12", I am still getting the error:

failed Building static HTML for pages - 5.220s
 ERROR #95312 
"navigator" is not available during server side rendering.
See our docs page for more info on this error: https://gatsby.dev/debug-html

  421 | 
  422 | var getIOS13 = function getIOS13() {
> 423 |   return navigator && (/iPad|iPhone|iPod/.test(navigator.platform) || navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1) && !window.MSStream;
      | ^
  424 | };
  425 | 
  426 | var getIPad13 = function getIPad13() {

  WebpackError: ReferenceError: navigator is not defined
  
  - main.js:423 getIOS13
    node_modules/react-device-detect/main.js:423:1
  
  - main.js:512 Object../node_modules/react-device-detect/main.js
    node_modules/react-device-detect/main.js:512:1

**Comment by duskload** [comment]
Add another update. If it's not working - try clear cache, for gatsby do something like:

`rm -rf node_modules && rm -rf ./cache && npm i && gatsby build && gatsby develop"

**Comment by PMhee** [comment]
I'm using version 1.11.13 but it is still bugging.
PS. I have tried to clean and clear cache already but it is not working

**Comment by gurkerl83** [comment]
I also confirm that in react-device-detect, version 1.11.13 navigator is not available. I`m using Nextjs, also server side rendered.

**Comment by SakshiSharma95** [comment]
it is not working when we are downgrading to a version . Please make sure whenever a new version is added it should not affect the previous version

**Comment by gurkerl83** [comment]
The last working version is 1.9.10.

**Comment by duskload** [comment]
@gurkerl83 , @SakshiSharma95 , @PMhee , updated package. Please verify if issue still persist

**Comment by stzonis** [comment]
@duskload version 1.11.14 works for me!

**Comment by elswenson** [comment]
@duskload Thank you for the quick fix and responsiveness!

**Comment by duskload** [comment]
Thanks guys!
