### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by chontawee** [duskload/react-device-detect#63]
When I start my app which use lib in latest version (1.11.14), I found error `navigator is not defined`. I think the problem is in `main.js` file.
`var getNavigatorInstance = function getNavigatorInstance() {
  if (typeof window !== 'undefined') {
    if (window.navigator || navigator) {
      return window.navigator || navigator;
    }
  }
`
I try to remove it from node_modules then it's work. But I'm not sure we can remove it from code or not. Can anybody confirm it?

**Comment by duskload** [comment]
@chontawee , that's strange. Are you using SSR? On what kind of device or browser do yo get this error?

**Comment by chontawee** [comment]
I used SSR. Are there any way to use this lib?

**Comment by duskload** [comment]
@chontawee What do you use for your SSR? (e.g gatsby, next.js or some custom SSR instead)

**Comment by thsnyzkn** [comment]
I am using next.js and it seems that isIE function seems to be not working. Thanks in advance.

**Comment by duskload** [comment]
Closing in favor of #75
