### ISSUE TITLE
Brave is detected as Chrome

### ISSUE THREAD

**Issue by SandroFernandes** [duskload/react-device-detect#67]
Hi ,
There's no way to distinguish Chrome from Brave, both return same browser name.
Saw some articles about finger printing brave , so it hides on chrome name. 
Is there a way to see the difference ?

**Comment by duskload** [comment]
@SandroFernandes , can you provide a brave browser user agent?

**Comment by duskload** [comment]
For now *Brave* detected as Chrome because they didn't add Brave to user agent. When they do this, it will be possible to detect Brave as a separated browser.

Closed so far.

**Comment by ssmith-wombatweb** [comment]
@duskload Brave now has navigator.brave which can be check to see if it is Brave Browser or not.

**Comment by SirKadogan** [comment]
@duskload is @mjoynes-wombat-web solutions something we can implement here to check if the browser is Brave?

I'm still getting chrome for it
