### ISSUE TITLE
This no longer works on iOS

### ISSUE THREAD

**Issue by bocodigital** [duskload/react-device-detect#69]
When testing a device in a hybrid app via xcode the deviceType returns as browser even though it is a native ios app.

**Comment by duskload** [comment]
@bocodigital, can you share a this hybrid app user agent?

**Comment by bocodigital** [comment]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)

**Comment by bocodigital** [comment]
It's pretty well documented as something Apple just randomly decided to change. My workaround was to use Ionics native device plugin.
