### ISSUE TITLE
Issue on IE

### ISSUE THREAD

**Issue by fawad-khalil-lunchon** [duskload/react-device-detect#71]
I am getting includes is not a function on IE due to this module. How can I use CommonJS version of it or atleast make it compatible to IE? I am using NextJS v8.1.0 and react-device-detect v1.6.2.

**Comment by cohancarpentier** [comment]
Not related to this library, but if you just need to detect IE here's what I did:

```
	<style>
		.hidden {
			opacity: 0;
		}
		.show {
			opacity: 1;
			margin-top: 16px;
		}
	</style>
	<body>
		<noscript>You need to enable JavaScript to run this app.</noscript>
		<div id="root"></div>
		<div id="ie" class="hidden">
			Sorry! We do not support your current browser. Please download
			<a href="https://www.google.com/chrome/">Google Chrome</a>,
			<a href="https://www.microsoft.com/en-us/edge">Microsoft Edge</a> or
			<a href="https://www.mozilla.org/en-CA/firefox/new/">Mozilla Firefox</a>.
		</div>
		<script>
			function msieversion() {
				var ua = window.navigator.userAgent
				var msie = ua.indexOf('MSIE ')

				if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) {
					document.getElementById('ie').classList.add('show')
				}
			}
			window.onload = msieversion
		</script>
	</body>
```

**Comment by duskload** [comment]
@fawad-khalil-lunchon , thanks for your report. I will rewrite this to make it compatible with IE.

So far you can use polyfill for supporting `includes` on IE.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Polyfill

**Comment by duskload** [comment]
Thanks @jtemplej for PR, issue will be available as soon as I update package (I think it will be in a couple days from now)
