### ISSUE TITLE
Jest unit testing mocking isMobile

### ISSUE THREAD

**Issue by mesutpiskin** [duskload/react-device-detect#72]
Hello, I developed an React application using the this package.
While writing the test code but my test didnt coverage the code because isMobile = false. How do I mock isMobile.

![Screen Shot 2020-02-25 at 15 57 26](https://user-images.githubusercontent.com/3519662/75249542-8d6cc880-57e7-11ea-9e0f-d35eda19158b.png)

my test code
```js
describe('<Header/>', () => {
  it('renders without crashing.', () => {
    
    const wrapper = mount(
      <MemoryRouter>
          <Header />
      </MemoryRouter>,
    );
    expect(wrapper.find(Header)).toHaveLength(1);
  });
});

```

**Comment by aquinq** [comment]
I faced the same problem using

```javascript
import { isMobile } from 'react-device-detect';

isMobile = true; // error : "isMobile" is read-only.
```

The following worked for me :

```javascript
import * as deviceDetect from 'react-device-detect';

deviceDetect.isMobile = true;
```

**Comment by duskload** [comment]
Thank you guys. That's actually the best option I've came up with myself. Will add this to docs. Feel free to reopen the issue if you have some questions.

**Comment by jordan-rigo** [comment]
> I faced the same problem using
> 
> ```js
> import { isMobile } from 'react-device-detect';
> 
> isMobile = true; // error : "isMobile" is read-only.
> ```
> 
> The following worked for me :
> 
> ```js
> import * as deviceDetect from 'react-device-detect';
> 
> deviceDetect.isMobile = true;
> ```

Am I the only one receving the same error with this import as well? 

version: 2.2.3

**Comment by Adomas202** [comment]
I had the same problem.

Need to additionally mock the returned value.

`jest.mock('react-device-detect', () => ({ isMobile: false }))`
