### ISSUE TITLE
SSR device detection is not working [continued]

### ISSUE THREAD

**Issue by czco** [duskload/react-device-detect#75]
[This issue](https://github.com/duskload/react-device-detect/issues/54) is still relevant. We've created a demo repo so you its easy to test  https://github.com/czco/next-isMobile-ssr

**Comment by duskload** [comment]
@czco Thanks! I will have a look as soon as I have time (till the end of this week)

**Comment by jatinvmehta** [comment]
@duskload - Was there any update on this ?

**Comment by duskload** [comment]
@jatinvmehta Sorry. Don't have much time for this package, due to high load on the other projects and work. If you have a solution, `PR` is always welcome.

**Comment by NimaKaviyani** [comment]
Anyone know another package for mobile and desktop detection?

**Comment by PaulPCIO** [comment]
@NimaKaviyani this should work fine using the user-agent in the req headers 
https://github.com/hgoebl/mobile-detect.js

```tsx
import mobileDetect from 'mobile-detect'

Page.getInitialProps = ({ req }) => {
    const md = new mobileDetect(req.headers['user-agent'])

    console.log( md.mobile() );                     // 'Sony'
    console.log( md.phone() );                      // 'Sony'
    console.log( md.tablet() );                     // null
    console.log( md.userAgent() );                  // 'Safari'
    console.log( md.os() );                         // 'AndroidOS'
    console.log( md.is('iPhone') );                 // false
    console.log( md.is('bot') );                    // false
    console.log( md.version('Webkit') );            // 534.3
    console.log( md.versionStr('Build') );          // '4.1.A.0.562'
    console.log( md.match('playstation|xbox') );    // false

    return { isMobile: md.mobile() ? true : false }
}
```

**Comment by PaulPCIO** [comment]
having a deeper look, you can use the same solution but instead with the same lib that `react-device-detect` is using, it would be better to leverage the [`ua-parser-js`](ua-parser-js) package by looking at the npm [trends](https://www.npmtrends.com/ua-parser-js-vs-mobile-detect)

The best solution though would be to enable a manual user-agent setter in the [`get-ua-data.js`](https://github.com/duskload/react-device-detect/blob/master/src/components/helpers/get-ua-data.js) helper

**Comment by PaulPCIO** [comment]
Anyone interested in a solution using `react-device-detect` i have added a userAgent argument to the [deviceDetect function](https://github.com/PaulPCIO/react-device-detect/blob/fd2ea71bc4867385ade7215788468303926f97a3/src/components/helpers/detect.js#L4-L7), which in turn leverages a [serverUA helper](https://github.com/PaulPCIO/react-device-detect/blob/fd2ea71bc4867385ade7215788468303926f97a3/src/components/helpers/get-ua-data.js#L13-L25) instead of the `browser` data, so now you can manually set the user agent to retrieve the relevant data.

@duskload I have not made a PR, let me know if I should? _(no tests added)_

repo: https://github.com/PaulPCIO/react-device-detect

**Comment by michaelnyu** [comment]
nice find @PaulPCIO !

**Comment by ha-ku** [comment]
Any update?

**Comment by zeing** [comment]
Support already ?

**Comment by RuiGuilherme** [comment]
You can use useEffect;

```javascript
import React, { useState, useEffect }
import { isMobile } from 'react-device-detect'

const App = () => {
  const [mobile, setMobile] = useState()

  useEffect(() => {
    setMobile(isMobile)
  }, [setMobile])

  return (
    <p>{ mobile ? "Mobile User" : "Non-Mobile User" }</p>
  )
}

export default App

```

**Comment by digz6666** [comment]
Currently I reverted back to version 1.9.10 and its working for me.

**Comment by jamesryan-dev** [comment]
oooo safe for this @digz6666 I'll do the same

**Comment by duskload** [comment]
It's possible to use it in SSR now, (for example in getInitialProps for next.js).

https://github.com/duskload/react-device-detect/blob/master/docs/api.md#utils--ssr

**Comment by samhstein** [comment]
just in case it helps... 
  
<   const userAgent = req['userAgent']
>  const userAgent = req ? req.headers['user-agent'] : navigator.userAgent;
 
Settings.getInitialProps = async ({ req }) => {
  const userAgent = req ? req.headers['user-agent'] : navigator.userAgent;
  const { isMobile, isMobileOnly } = getSelectorsByUserAgent(userAgent);
  return {
    isMobile: isMobile,
    isMobileOnly: isMobileOnly,
  }
}

**Comment by RomanSkrypnik** [comment]
What's the purpose of this lib exactly? Even such functionality for SSR is not prepared
Why nuxt js has SSR support under the hood while this lib doesn't
