### ISSUE TITLE
withOrientationChange HOC does not work properly on iPad iOS 13

### ISSUE THREAD

**Issue by chepicov** [duskload/react-device-detect#79]
`isLandscape` and `isPortrait` properties always return false.

User-agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`

**Comment by chepicov** [comment]
This is because of `isMobile` check here, which doesn't work correctly for iPad on iOS 13:
https://github.com/duskload/react-device-detect/blob/27e1b838c9e2eea635a7f1ceefb03feb8a666d4d/src/components/helpers/withOrientationChange.js#L43

Possible solution:
https://github.com/chepicov/react-device-detect/commit/a07e84e97698740b39393eca5fc35caea26bc587

**Comment by duskload** [comment]
Thanks @chepicov , should work now.
