### ISSUE TITLE
doesn't work on ipad safari browser 

### ISSUE THREAD

**Issue by GAUTAMRAJU15** [duskload/react-device-detect#80]
i have tried **isMobile** as well as **isTablet** properties , on safari, it's always false, but on chrome it's true on ipad

**Comment by chepicov** [comment]
I've fixed with #55 
e.g. `const tablet = (): boolean => isTablet || isIPad13`

**Comment by duskload** [comment]
@GAUTAMRAJU15, can you check please if it still relevant after last update?

**Comment by GAUTAMRAJU15** [comment]
actually when i removed isIPAD13 it didn't work 
```isTablet || isIPad13``` this  works, 
i guess that PR didn't help

browserFullVersion
:
"13.0.1"


browserName
:
"Safari"
engineName
:
"WebKit"

engineVersion
:
"605.1.15"

osName
:
"Mac OS"

osVersion
:
"10.15"
