### ISSUE TITLE
osName enums

### ISSUE THREAD

**Issue by manemmao** [duskload/react-device-detect#83]
I think its better to add osName enumsto docs. 
By now just two of os name enums are specified in docs:
`returns os name (e.g Windows, Android)`
In my case I should send to server specific enums based on OS and need to know exactly what os names should I expected from this method to add to my local switch.

**Comment by duskload** [comment]
Hi, @manemmao. I actually was planning to export enums, but I don't know when I going to have time for this.

**Comment by duskload** [comment]
Added enums.
