### ISSUE TITLE
Is it possible to detect our device being accessed on a native device or desktop browser in mobile mode?

### ISSUE THREAD

**Issue by wisnuvb** [duskload/react-device-detect#87]
I want to know if it is possible to find out the device that accesses us is a native phone or browser with mobile mode. If it can be known that we will be extraordinary. Thanks

**Comment by duskload** [comment]
@wisnuvb, I don't get it what you need. Do you need to detect that user runs your site from a mobile device, but not a 'mobile' simulation in a browser?

**Comment by wisnuvb** [comment]
@duskload, Correctly. I mean like that. Is that possible?

**Comment by duskload** [comment]
@wisnuvb I think it's possible. But I don't have time now for investigation and implementation of this. I will accept PR thought

**Comment by wisnuvb** [comment]
Thanks @duskload
