### ISSUE TITLE
isIE always true for Chrome and Brave browsers

### ISSUE THREAD

**Issue by ShaneYu** [duskload/react-device-detect#88]
For some reason isIE is always true when imported in typescript for my react application when the browser is Chrome or Brave.

My User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Package Version: ^1.12.1

**Comment by duskload** [comment]
@ShaneYu Can't reproduce this bug on given user agent, for chrome and brave browsers. Is this bug still relevant

**Comment by ShaneYu** [comment]
> @ShaneYu Can't reproduce this bug on given user agent, for chrome and brave browsers. Is this bug still relevant?

I’ve removed it completely and re-added the latest version. After doing that, it’s started working. Had some very odd behaviour, wonder if it didn’t install properly the first time or something.

Apologies for wasting your time, but thanks for the quick response. I am now using it will success doing what I needed to do all along.

Thanks for the package, it’s very useful! 🙂

**Comment by duskload** [comment]
@ShaneYu No problem, and thanks! Feel free to open an issue if you have some problems.
