### ISSUE TITLE
isIE still show false

### ISSUE THREAD

**Issue by aolba** [duskload/react-device-detect#9]
I see there is a close issue about detection with IE and there was an update for that, But I'm not sure if there is something more I need. I have the same behavior with IE11. String is showing IE, but the Boolean display false.
This is the version I have "react-device-detect": "^1.4.5"

**Comment by duskload** [comment]
@aolba 
Can you please provide me a user agent of this IE11 browser?

**Comment by duskload** [comment]
I've fixed this. Update the package and it will be available for you.

**Comment by aolba** [comment]
Thanks for fix it.
