### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by ppsirius** [duskload/react-device-detect#90]
I try to use this lib in React app but got an error with "includes" on IE 11. 
It will be good to know what browsers you support to avoid that kind of situation or transpile to older version.
Most people I think exclude node_module from transpilation so better to know what exactly library support.

**Comment by duskload** [comment]
@ppsirius , what version of package do you use? All `includes` was rewritten to `indexOf` a while ago. Try update the package to @latest version.

**Comment by ppsirius** [comment]
I was using older version 1.11.14 :|
But it will be great that babel use browserlist for example from package.json

I don't know how exactly @babel/preset-env rollup plugin works but in webpack by default read that kind of thing from package.json.
`  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie < 11",
    "not op_mini all"
  ],`
Then you are sure that compatibility js features be handled by babel transpiler.

**Comment by duskload** [comment]
Right now application should support all browsers, if it's not - feel free to file an issue with example.
