### ISSUE TITLE
Edge-Chromium 83 isn't being detected

### ISSUE THREAD

**Issue by avshalomt2** [duskload/react-device-detect#94]
See here: https://n8wx0.csb.app/
In Edge 83 (Chromium-based), this is the output:

```
react-device-detect
This is desktop
{
    "isMobile": false,
    "chrome": {
        "isChrome": false,
        "isChromium": false
    },
    "edge": {
        "isEdge": true,
        "isEdgeChromium": false,
        "isLegacyEdge": true
    },
    "isFirefox": false,
    "isSafari": false,
    "isOpera": false,
    "browser": {
        "browserName": "Edge",
        "browserVersion": "83",
        "fullBrowserVersion": "83.0.478.64"
    },
    "engine": {
        "engineName": "Blink",
        "engineVersion": "83.0.4103.116"
    },
    "getUA": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.64"
}
```

isEdgeChromium should be true, isLegacyEdge should be false, and I think that isChromium should be true as well, since it's a Chromium-based browser (as stated in it's about page).
Starting from Edge 79, it is Chromium based.

**Comment by avshalomt2** [comment]
On Windows 10 it seems to behave differently:
![image](https://user-images.githubusercontent.com/47110179/87655569-1b2e5d80-c761-11ea-85d4-2617a094e1b7.png)

**Comment by a-lchen** [comment]
Hi there! We've run into this same bug, except with Edge 84. This string is detecting as Legacy Edge:

Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36 Edg/84.0.522.59

Changing windows to window 10 seems to fix this issue.
