### ISSUE TITLE
isTouch

### ISSUE THREAD

**Issue by edhenderson** [duskload/react-device-detect#96]
Fantastic repo, thank you.

Wondering if there is a suggested method to emulate an `isTouch` type scenario. My best guess so far based on your entry points is something like?

```javascript
public static hasTouchScreen(): boolean {
    return isAndroid || isWinPhone || isIOS;
}
```

Thank you in advance.

**Comment by andrewpaulino** [comment]
I am assuming you are referring to something like [https://stackoverflow.com/questions/7838680/detecting-that-the-browser-has-no-mouse-and-is-touch-only](this) right? It seems media queries in CSS4 are a cool way of doing that. As of right now, I do not believe you can really tell from the browser besides formulating your own solution.

**Comment by edhenderson** [comment]
Yes, something like. I was thinking similar, thanks for taking the time to reply.
