### ISSUE TITLE
isMobileSafari giving true when in Chrome on Macbook

### ISSUE THREAD

**Issue by alex-cory** [duskload/react-device-detect#99]
![image](https://user-images.githubusercontent.com/5455859/90694292-3fcc9800-e22d-11ea-980d-982d82e795d3.png)
Looks like it might actually be a problem with `isSafari` because when in chrome, it shows `true`
![image](https://user-images.githubusercontent.com/5455859/90694511-976b0380-e22d-11ea-93ac-a0b2ac46a427.png)

**Comment by alex-cory** [comment]
Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1

**Comment by duskload** [comment]
That's an iPhone user agent.

You might be switching it with some extension, for example?
You can get current user agent of chrome browser from console with `window.navigator.userAgent`

For example I have the following user agent of my mac:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

**Comment by swannknani** [comment]
You're using chrome dev tools in mobile.
Click on the top left blue mobile icon on your chrome window to switch back to the desktop view.

<img width="454" alt="Screenshot 2020-08-26 at 18 13 07" src="https://user-images.githubusercontent.com/1637657/91335127-e386ec80-e7c7-11ea-9dd8-e916f1ff979a.png">

**Comment by alex-cory** [comment]
shouldn't it work on mobile view?

**Comment by swannknani** [comment]
Yes it works, and you are emulating an `iPhone X` that's why it return `isSafari=true`...

**Comment by alex-cory** [comment]
oh duh
